#! /usr/bin/env bash
dbfile=$1

sqlitecmd=$(which sqlite3)

#"${FILE%%.*}"
# %Y-%m-%d%nTIME: %H:%M:%S"
dbfilename="$(basename $dbfile)"
dbfilenamenoext="${dbfilename%%.*}"

backupfile="$dbfilenamenoext-$(date  +"%Y-%m-%d-%H%M%S").db"
$sqlitecmd <<SQL
.backup  $backupfile
.quit
SQL